### ISSUE TITLE
App builds failing on node v14 due to "node:" require prefix

### ISSUE THREAD

**Issue by ravinsp** [unjs/rc9#20]
Seems the recent package release 1.2.3 is using requires with "node:" prefix ([this commit](https://github.com/unjs/rc9/commit/f76dd93046e4fc5ef9736e2a16340095b67cc23d)) which is not compatible with node v14. Our application uses NuxtJs and NuxtJs is using rc9. Now our application build is failing. I imagine this would be the case with lot of projects using rc9 who wants to maintain compatibility with node v14.

Since this "node:" prefix update has been released as a minor version update, lot of packages which are using rc9 must be automatically using 1.2.3 now and it should fail the build on node v14 for lot of such projects.

Can you suggest a way to fix this at the application level? Thank you.

Build error we are getting:
```
Error: Cannot find module 'node:fs'
Require stack:
- /app/node_modules/rc9/dist/index.cjs
- /app/node_modules/@nuxt/config/dist/config.js
- /app/node_modules/@nuxt/cli/dist/cli-index.js
- /app/node_modules/@nuxt/cli/dist/cli.js
- /app/node_modules/nuxt/bin/nuxt.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/node_modules/rc9/dist/index.cjs:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/rc9/dist/index.cjs',
    '/app/node_modules/@nuxt/config/dist/config.js',
    '/app/node_modules/@nuxt/cli/dist/cli-index.js',
    '/app/node_modules/@nuxt/cli/dist/cli.js',
    '/app/node_modules/nuxt/bin/nuxt.js'
  ]
```

**Comment by pi0** [comment]
Sorry for the inconvenience. Reverted 1.x latest to 1.2.2 that is not using `node:` protocol`.

BTW normally, if you install latest 14.x, it is backported to `v14.13.1`.
